#!/bin/bash

# Mostly inspired by https://github.com/trion-development/docker-ng-cli/blob/master/hooks/post_push
# Download manifest-tool
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

# Tag as latest
TAG_VER=$(echo "${DOCKER_TAG}" |  rev | cut -d- -f2- | rev )
if [[ ! $TAG_VER =~ (-beta|-test) ]]; then
    echo "Tagging version ${TAG_VER} as latest..."
    TAG_LATEST=$(echo "${DOCKER_TAG}" | sed s/${TAG_VER}/latest/g)
    docker tag $IMAGE_NAME $DOCKER_REPO:$TAG_LATEST
    docker push $DOCKER_REPO:$TAG_LATEST
    
    # Write "latest" manifest
    ./manifest-tool push from-args --ignore-missing \
    --platforms linux/amd64,linux/arm,linux/arm64 \
    --template $DOCKER_REPO:latest-ARCH \
    --target $DOCKER_REPO:latest
else
    echo "Test version detected (${TAG_VER}), not tagging it as latest..."
fi

# Write manifest
./manifest-tool push from-args --ignore-missing \
--platforms linux/amd64,linux/arm,linux/arm64 \
--template $DOCKER_REPO:${TAG_VER}-ARCH \
--target $DOCKER_REPO:${TAG_VER}